
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 04 18:40:04 GMT-03:00 2017
//----------------------------------------------------

package codigos;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int PORCENTAGEM = 29;
  public static final int MENORQ = 36;
  public static final int INPUT = 13;
  public static final int DIFERENTE = 37;
  public static final int MAIORQ = 35;
  public static final int COMENTARIOS = 46;
  public static final int INT = 42;
  public static final int PARESQ = 31;
  public static final int FOR = 8;
  public static final int VIRGULA = 47;
  public static final int NOT = 18;
  public static final int IS = 22;
  public static final int AND = 20;
  public static final int IGUAL = 34;
  public static final int RANGE = 10;
  public static final int PASS = 17;
  public static final int IN = 21;
  public static final int OR = 19;
  public static final int MAIS = 25;
  public static final int ISNOT = 23;
  public static final int IF = 4;
  public static final int ID = 43;
  public static final int RETORNO = 16;
  public static final int EOF = 0;
  public static final int MENORIGUALQ = 38;
  public static final int TRUE = 12;
  public static final int error = 1;
  public static final int COMENTARIO = 45;
  public static final int NEWLINE = 3;
  public static final int MENOS = 26;
  public static final int MAIORIGUALQ = 39;
  public static final int DOISIGUAIS = 30;
  public static final int PARDIR = 32;
  public static final int BREAK = 9;
  public static final int IDENT = 2;
  public static final int DIVISAO = 28;
  public static final int NOTIN = 24;
  public static final int ELSE = 6;
  public static final int CONCATENACAO = 40;
  public static final int WHILE = 7;
  public static final int FLOAT = 41;
  public static final int FALSO = 11;
  public static final int STRING = 44;
  public static final int DEF = 15;
  public static final int ELIF = 5;
  public static final int VEZES = 27;
  public static final int PRINT = 14;
  public static final int DOISPONTOS = 33;
}

